import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Empleado from '#models/empleado'
import { DateTime } from 'luxon'

export default class EmpleadoSeeder extends BaseSeeder {
  async run () {
    await Empleado.createMany([
      {
        numero: 1001,
        nombre: 'Juan',
        paterno: 'Pérez',
        materno: 'García',
        grupoId: 1,
        plantaId: 1,
        departamentoId: 1,
        rfidUid: '04A3BC56D1',
        fingerprintId: 'FP001',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2023-01-15'),
        fecha_baja: null,
      },
      {
        numero: 1002,
        nombre: 'María',
        paterno: 'López',
        materno: 'Hernández',
        grupoId: 1,
        plantaId: 1,
        departamentoId: 2,
        rfidUid: '04A3BC56D2',
        fingerprintId: 'FP002',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2022-10-01'),
        fecha_baja: null,
      },
      {
        numero: 1003,
        nombre: 'Carlos',
        paterno: 'Ramírez',
        materno: 'Santos',
        grupoId: 2,
        plantaId: 1,
        departamentoId: 1,
        rfidUid: '04A3BC56D3',
        fingerprintId: 'FP003',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2021-07-20'),
        fecha_baja: null,
      },
      {
        numero: 1004,
        nombre: 'Laura',
        paterno: 'Fernández',
        materno: 'Gómez',
        grupoId: 2,
        plantaId: 2,
        departamentoId: 2,
        rfidUid: '04A3BC56D4',
        fingerprintId: 'FP004',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2020-05-10'),
        fecha_baja: null,
      },
      {
        numero: 1005,
        nombre: 'Luis',
        paterno: 'Martínez',
        materno: 'Núñez',
        grupoId: 3,
        plantaId: 1,
        departamentoId: 3,
        rfidUid: '04A3BC56D5',
        fingerprintId: 'FP005',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2019-09-12'),
        fecha_baja: null,
      },
      {
        numero: 1006,
        nombre: 'Ana',
        paterno: 'Castro',
        materno: 'Salas',
        grupoId: 3,
        plantaId: 2,
        departamentoId: 1,
        rfidUid: '04A3BC56D6',
        fingerprintId: 'FP006',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2021-03-18'),
        fecha_baja: null,
      },
      {
        numero: 1007,
        nombre: 'Jorge',
        paterno: 'Vargas',
        materno: 'Reyes',
        grupoId: 1,
        plantaId: 1,
        departamentoId: 2,
        rfidUid: '04A3BC56D7',
        fingerprintId: 'FP007',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2022-06-25'),
        fecha_baja: null,
      },
      {
        numero: 1008,
        nombre: 'Elena',
        paterno: 'Silva',
        materno: 'Ortega',
        grupoId: 2,
        plantaId: 2,
        departamentoId: 3,
        rfidUid: '04A3BC56D8',
        fingerprintId: 'FP008',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2020-11-30'),
        fecha_baja: null,
      },
      {
        numero: 1009,
        nombre: 'Roberto',
        paterno: 'Flores',
        materno: 'Delgado',
        grupoId: 1,
        plantaId: 1,
        departamentoId: 3,
        rfidUid: '04A3BC56D9',
        fingerprintId: 'FP009',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2023-02-10'),
        fecha_baja: null,
      },
      {
        numero: 1010,
        nombre: 'Gabriela',
        paterno: 'Sánchez',
        materno: 'Moreno',
        grupoId: 3,
        plantaId: 1,
        departamentoId: 1,
        rfidUid: '04A3BC56DA',
        fingerprintId: 'FP010',
        activo: true,
        fecha_ingreso: DateTime.fromISO('2018-08-05'),
        fecha_baja: null,
      },
    ])
  }
}
